---
- name: Deploy Nginx Container
  hosts: jenkins
  become: true
  tasks:
    - name: Pull nginx image
      docker_image:
        name: nginx
        source: pull

    - name: Run nginx container
      docker_container:
        name: nginx
        image: nginx:latest
        state: started
        restart_policy: always
        published_ports:
          - "80:80"
