---
# tasks file for roles/docker

- name: Update apt cache
  apt:
    update_cache: yes
- name: Install docker
  apt:
    name: docker.io
    state: present
- name: Enable docker service
  service:
    name: docker
    state: started
    enabled: yes
- name: Add ubuntu user to docker group
  user:
    name: ubuntu
    groups: docker
    append: yes
- name: Install Python Docker SDK
  apt:
    name: python3-docker
    state: present
- name: Pull nginx image
  docker_image:
    name: nginx
    source: pull
- name: Run nginx container
  docker_container:
     name: nginx
     image: nginx:latest
     state: started
        restart_policy: always
        published_ports:
          - "80:80"
